from time import strftime as now
from pathlib import Path as path


# ------------------------------------------ #
#           RECORDLIST PARAMETERS            #
# ------------------------------------------ #
WINDOWS_SIZE = (1280, 650)
WINDOWS_LOCATION = (0, 0)

# ------------------------------------------ #
#               DATE AND TIME                #
# ------------------------------------------ #
def DATE() -> str:
    return now('%d/%m/%Y')


def TIME() -> str:
    return now('%H:%M')


# ------------------------------------------ #
#                    PATH                    #
# ------------------------------------------ #
JSON_STOCK_PATH = './db/Stock.json'
JSON_SALES_PATH = './db/Sales.json'
JSON_BUYS_PATH = './db/Buys.json'
JSON_PATHS = (JSON_STOCK_PATH, JSON_SALES_PATH, JSON_BUYS_PATH)
CSV_SALES_PATH = './db/Sales.csv'
CSV_BUYS_PATH = './db/Buys.csv'
DESKTOP = str(path.home()).replace('\\', '/') + '/Desktop/'

# ------------------------------------------ #
#               CSV HEADERS                  #
# ------------------------------------------ #
CSV_HEADER = [[DATE(), TIME()]]
CSV_STOCK_HEADER = CSV_HEADER + [['NOMBRE', 'PRECIO POR UNIDAD', 'STOCK']]
CSV_SALES_HEADER = [
    [
        'DÍA', 'HORA', 'NOMBRE', 'PRECIO POR UNIDAD', 'STOCK',
        'CANTIDAD VENDIDA', 'PRECIO FINL'
    ]
]
CSV_BUYS_HEADER = [
    [
        'DÍA', 'HORA', 'NOMBRE', 'PRECIO POR UNIDAD', 'STOCK',
        'CANTIDAD COMPRADA', 'PRECIO FINL', 'PROVEEDOR'
    ]
]

# ------------------------------------------ #
#             RECORD PARAMETERS              #
# ------------------------------------------ #
R_TMP_SIZE = (5, 1)
R_TMP_PAD = (0, 1)
STOCK_NAME_SIZE = (78, 1)
SALE_NAME_SIZE = (65, 1)
BUY_NAME_SIZE = (50, 1)
NAME_PAD = R_TMP_PAD
UNIT_PRICE_SIZE = (8, 1)
UNIT_PRICE_PAD = R_TMP_PAD
STOCK_SIZE = (5, 1)
STOCK_PAD = R_TMP_PAD
SPIN_SIZE = (5, 1)
SPIN_PAD = R_TMP_PAD
SPIN_VALUES = [i for i in range(-100, 101, 5)]
CHECK_PAD = R_TMP_PAD
AMOUNT_SIZE = (5, 1)
AMOUNT_PAD = R_TMP_PAD
FINAL_PRICE_SIZE = (8, 1)
FINAL_PRICE_PAD = R_TMP_PAD
SUPPLIER_SIZE = (15, 1)
SUPPLIER_PAD = R_TMP_PAD

# ------------------------------------------ #
#           RECORDLIST PARAMETERS            #
# ------------------------------------------ #
RL_TMP_SIZE = (1241, 300)
RL_TMP_PAD = (0, 1)
RECORDLIST_COLUMN_SIZE = RL_TMP_SIZE
RECORDLIST_COLUMN_PAD = RL_TMP_PAD
SALELIST_COLUMN_SIZE = RL_TMP_SIZE
SALELIST_COLUMN_PAD = RL_TMP_PAD
BUYLIST_COLUMN_SIZE = RL_TMP_SIZE
BUYLIST_COLUMN_PAD = RL_TMP_PAD

# ------------------------------------------ #
#               SECTION SIZES                #
# ------------------------------------------ #
RL_S_TMP_SIZE = (1258, 398)
RL_S_TMP_PAD = ((0, 0), (0, 0))
STOCKLIST_S_SIZE = RL_S_TMP_SIZE
STOCKLIST_S_PAD = RL_S_TMP_PAD
SALELIST_S_SIZE = RL_S_TMP_SIZE
SALELIST_S_PAD = RL_S_TMP_PAD
BUYSECTION_S_SIZE = RL_S_TMP_SIZE
BUYSECTION_S_PAD = RL_S_TMP_PAD
TAB_GROUP_PAD = ((0, 0), (0, 0))
TAB_GROUP_BORDER_WIDTH = 0
TAB_PAD =  ((0, 0), (0, 0))
TAB_BORDER_WIDTH =  0

# ------------------------------------------ #
#             SECTION PARAMETERS             #
# ------------------------------------------ #
S_TMP_SIZE = (5, 5)
S_TMP_PAD = ((0, 0), (0, 0))
FINDER_INPUT_KEY = ',finder_input'
FINDER_INPUT_SIZE = (20, 1)
FINDER_INPUT_PAD = ((5, 0), (0, 0))
FINDER_BUTTON_KEY = ',search'
FINDER_BUTTON_PAD = S_TMP_PAD
FINDER_BUTTON_TEXT = '🔍'
FINDER_BUTTON_TOOLTIP = ''
SORTER_COMBO_KEY = ',sorter_option'
SORTER_COMBO_SIZE = (10, 1)
SORTER_COMBO_PAD = S_TMP_PAD
SORTER_COMBO_TOOLTIP = ''
SORTER_COMBO_STOCK_VALUES = ['NOMBRE', 'PU', 'STOCK']
SORTER_COMBO_SALES_VALUES = [
    'NOMBRE', 'PU', 'STOCK', 'CANTIDAD', 'PF'
]
SORTER_COMBO_BUYS_VALUES = [
    'NOMBRE', 'PU', 'STOCK', 'CANTIDAD', 'PF',
    'PROVEEDOR'
]
SORTER_COMBO_ALL_VALUES = {
    'NOMBRE': 0, 'PU': 1, 'STOCK': 2, 'CANTIDAD': 3, 'PF': 4,
    'PROVEEDOR': 5
}
SORTER_BUTTON_UP_KEY = ',sort_list_min_max'
SORTER_BUTTON_DOWN_KEY = ',sort_list_max_min'
SORTER_BUTTON_PAD = S_TMP_PAD
SORTER_BUTTON_UP_TEXT = '⬊'
SORTER_BUTTON_DOWN_TEXT = '⬋'
SORTER_BUTTON_UP_TOOLTIP = ''
SORTER_BUTTON_DOWN_TOOLTIP = ''
CLEANER_COMBO_KEY = ',cleaner_option'
CLEANER_COMBO_SIZE = (15, 1)
CLEANER_COMBO_PAD = S_TMP_PAD
CLEANER_BUTTON_KEY = ',remove_records'
CLEANER_BUTTON_PAD = S_TMP_PAD
CLEANER_BUTTON_TEXT = '―'
CLEANER_BUTTON_TOOLTIP = ''
APPLY_BUTTON_KEY = ',apply'
APPLY_BUTTON_PAD = S_TMP_PAD
APPLY_BUTTON_TEXT = '✔'
APPLY_BUTTON_TOOLTIP = ''
INDEX_RADIO_SIZE = S_TMP_SIZE
INDEX_RADIO_PAD = S_TMP_PAD
INDEX_COLUMN_PAD = S_TMP_PAD
INDEX_INPUT_STOCK_NAME_SIZE = STOCK_NAME_SIZE
INDEX_INPUT_SALE_NAME_SIZE = SALE_NAME_SIZE
INDEX_INPUT_BUY_NAME_SIZE = BUY_NAME_SIZE
INDEX_INPUT_NAME_PAD = ((5, 0), (0, 0))
INDEX_INPUT_NAME_TEXT = 'NOMBRE'
INDEX_INPUT_UNIT_PRICE_SIZE = UNIT_PRICE_SIZE
INDEX_INPUT_UNIT_PRICE_PAD = S_TMP_PAD
INDEX_INPUT_UNIT_PRICE_TEXT = 'PU'
INDEX_INPUT_STOCK_SIZE = S_TMP_SIZE
INDEX_INPUT_STOCK_PAD = S_TMP_PAD
INDEX_INPUT_STOCK_TEXT = 'STOCK'
INDEX_INPUT_PERCENT_SIZE = SPIN_SIZE
INDEX_INPUT_PERCENT_PAD = S_TMP_PAD
INDEX_INPUT_PERCENT_TEXT = '%'
INDEX_INPUT_FINAL_PRICE_SIZE = FINAL_PRICE_SIZE
INDEX_INPUT_FINAL_PRICE_PAD = S_TMP_PAD
INDEX_INPUT_FINAL_PRICE_TEXT = 'PF'
INDEX_INPUT_AMOUNT_SIZE = AMOUNT_SIZE
INDEX_INPUT_AMOUNT_PAD = S_TMP_PAD
INDEX_INPUT_AMOUNT_TEXT = 'CANTIDAD'
INDEX_INPUT_SUPPLIER_SIZE = SUPPLIER_SIZE
INDEX_INPUT_SUPPLIER_PAD = S_TMP_PAD
INDEX_INPUT_SUPPLIER_TEXT = 'PROVEEDOR'
ADDER_SPIN_KEY = ',spin_adder'
ADDER_SPIN_SIZE = SPIN_SIZE
ADDER_SPIN_PAD = S_TMP_PAD
ADDER_SPIN_VALUES = [i for i in range(1, 30, 2)]
ADDER_BUTTON_KEY = ',add_records'
ADDER_BUTTON_PAD = S_TMP_PAD
ADDER_BUTTON_TEXT = '＋'
ADDER_BUTTON_TOOLTIP = '',
STOCK_SECTION_CLEANER_OPTIONS = ['SELECCIONADOS', 'VACÍOS']
SALE_SECTION_CLEANER_OPTIONS = ['SELECCIONADOS']
SAVE_AS_BUTTON_KEY = ',save_as'
SAVE_AS_BUTTON_PAD = S_TMP_PAD
SAVE_AS_BUTTON_TEXT = '💾'
SAVE_AS_BUTTON_TOOLTIP = ''
SAVE_AS_BUTTON_INITIAL_FOLDER = DESKTOP + f'Reporte {DATE()} {TIME()}.csv'
COMMERCE_BUTTON_KEY = ',commerce'
COMMERCE_BUTTON_PAD = S_TMP_PAD
COMMERCE_BUTTON_TEXT = '💲'
COMMERCE_BUTTON_TOOLTIP = ''
TOTAL_PRICE_KEY = 'total_price'
TOTAL_PRICE_SIZE = S_TMP_SIZE
TOTAL_PRICE_PAD = S_TMP_PAD
PRE_VISULIZATOR_BUTTON_KEY = ',pre_visualizator'
PRE_VISULIZATOR_BUTTON_PAD = S_TMP_PAD
PRE_VISULIZATOR_BUTTON_TEXT = '☶'
PRE_VISULIZATOR_BUTTON_TOOLTIP = ''

BUTTON_IMAGE = b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAA9ElEQVQ4T3VTWRYDMQiS+x/aPgWX2HY+ZkkiAjKwuJB3g5s5+Om6c6E24qmzhnxVKRf7AiGiOI/BzBtIHREtYEAcdi9gMqn6g+nZnaAikl9N63n/U5zi2FPNEkAo2mhMqFsfLilRQ2lt2euBiKZLbnDISyIVfZ46moIfwpO091KS7dmcTqwpFPGRU9PrebVzBI4BSMIQmwxwbTxebmc02JsTO80rW6N1RUQesE45cM0kKOWET9qaSQleyM0g9Na1O++Zn7xSwkzyB2FpfXP6JkypLev4gxCaUr5NLN9rf0f5B8c97zdA5NU5eLSuP/icksGT7Q/rqoAi4wjvpQAAAABJRU5ErkJggg=='
# BUTTON_IMAGE = None
BUTTON_IMAGE_SIZE = (52, 22)
