from time import strftime as now
from pathlib import Path as path

# ------------------------------------------ #
#           RECORDLIST PARAMETERS            #
# ------------------------------------------ #
WINDOWS_SIZE = (1276, 656)
WINDOWS_LOCATION = (0, 0)


# ------------------------------------------ #
#               DATE AND TIME                #
# ------------------------------------------ #
def DATE() -> str:
    return now('%d/%m/%Y')


def TIME() -> str:
    return now('%H:%M')


# ------------------------------------------ #
#                    PATH                    #
# ------------------------------------------ #
JSON_STOCK_PATH = './db/Stock.json'
JSON_SALES_PATH = './db/Sales.json'
JSON_BUYS_PATH = './db/Buys.json'
JSON_PATHS = (JSON_STOCK_PATH, JSON_SALES_PATH, JSON_BUYS_PATH)
CSV_SALES_PATH = './db/Sales.csv'
CSV_BUYS_PATH = './db/Buys.csv'
DESKTOP = str(path.home()).replace('\\', '/') + '/Desktop/'

# ------------------------------------------ #
#               CSV HEADERS                  #
# ------------------------------------------ #
CSV_HEADER = [[DATE(), TIME()]]
CSV_STOCK_HEADER = CSV_HEADER + [['NOMBRE', 'PRECIO POR UNIDAD', 'STOCK']]
CSV_SALES_HEADER = [
    [
        'DÍA', 'HORA', 'TOTAL', 'NOMBRE', 'PRECIO UNIDAD', 'STOCK', 'VENDIDOS',
        'PRECIO FINAL'
    ]
]
CSV_BUYS_HEADER = [
    [
        'DÍA', 'HORA', 'TOTAL', 'NOMBRE', 'PRECIO UNIDAD', 'STOCK', 'COMPRADOS',
        'PRECIO FINAL', 'PROVEEDOR'
    ]
]

# ------------------------------------------ #
#             RECORD PARAMETERS              #
# ------------------------------------------ #
# TMP
R_TMP_PAD = ((0, 0), (0, 0))
# GENERIC
RECORD_PAD = R_TMP_PAD
# NAME
STOCK_NAME_SIZE = (79, 1)
SALE_NAME_SIZE = (62, 1)
BUY_NAME_SIZE = (49, 1)
NAME_PAD = R_TMP_PAD
# UNIT_PRICE
UNIT_PRICE_SIZE = (7, 1)
UNIT_PRICE_PAD = R_TMP_PAD
# STOCK
STOCK_SIZE = (6, 1)
STOCK_PAD = R_TMP_PAD
# SPIN
SPIN_SIZE = (5, 1)
SPIN_PAD = R_TMP_PAD
SPIN_VALUES = [i for i in range(-100, 101, 5)]
# CHECK
CHECK_PAD = R_TMP_PAD
# AMOUNT
AMOUNT_SIZE = (9, 1)
AMOUNT_PAD = R_TMP_PAD
# FINAL_PRICE
FINAL_PRICE_SIZE = (7, 1)
FINAL_PRICE_PAD = R_TMP_PAD
# SPPLIER
SUPPLIER_SIZE = (12, 1)
SUPPLIER_PAD = R_TMP_PAD

# ------------------------------------------ #
#           RECORDLIST PARAMETERS            #
# ------------------------------------------ #
RL_TMP_SIZE = (1241, 180)
RL_TMP_PAD = (0, 1)
RECORDLIST_COLUMN_SIZE = (1241, 290)
RECORDLIST_COLUMN_PAD = RL_TMP_PAD
SALELIST_COLUMN_SIZE = RL_TMP_SIZE
SALELIST_COLUMN_PAD = RL_TMP_PAD
BUYLIST_COLUMN_SIZE = RL_TMP_SIZE
BUYLIST_COLUMN_PAD = RL_TMP_PAD

# ------------------------------------------ #
#               SECTION SIZES                #
# ------------------------------------------ #
RL_S_TMP_SIZE = (1258, 398)
RL_S_TMP_PAD = ((0, 0), (0, 0))
STOCKLIST_S_SIZE = (1258, 360)
STOCKLIST_S_PAD = RL_S_TMP_PAD
SALELIST_S_SIZE = (1258, 250)
SALELIST_S_PAD = RL_S_TMP_PAD
BUYSECTION_S_SIZE = (1258, 250)
BUYSECTION_S_PAD = RL_S_TMP_PAD
TAB_GROUP_PAD = ((0, 0), (0, 0))
TAB_GROUP_BORDER_WIDTH = 0
TAB_PAD = ((0, 0), (0, 0))
TAB_BORDER_WIDTH = 0

# ------------------------------------------ #
#             SECTION PARAMETERS             #
# ------------------------------------------ #
DEFAULT_SAVE_TARGET = 9
# TMP
S_TMP_SIZE = (5, 1)
S_TMP_PAD = ((4, 4), (0, 0))
# INDEX
INDEX_TMP_PAD = ((0, 0), (2, 0))
INDEX_RADIO_SIZE = S_TMP_SIZE
INDEX_RADIO_PAD = INDEX_TMP_PAD
INDEX_COLUMN_PAD = INDEX_TMP_PAD
INDEX_INPUT_STOCK_NAME_SIZE = STOCK_NAME_SIZE
INDEX_INPUT_SALE_NAME_SIZE = SALE_NAME_SIZE
INDEX_INPUT_BUY_NAME_SIZE = BUY_NAME_SIZE
INDEX_INPUT_NAME_PAD = INDEX_TMP_PAD
INDEX_INPUT_NAME_TEXT = 'NOMBRE'
INDEX_INPUT_UNIT_PRICE_SIZE = UNIT_PRICE_SIZE
INDEX_INPUT_UNIT_PRICE_PAD = INDEX_TMP_PAD
INDEX_INPUT_UNIT_PRICE_TEXT = 'PU'
INDEX_INPUT_STOCK_SIZE = STOCK_SIZE
INDEX_INPUT_STOCK_PAD = INDEX_TMP_PAD
INDEX_INPUT_STOCK_TEXT = 'STOCK'
INDEX_INPUT_PERCENT_SIZE = SPIN_SIZE
INDEX_INPUT_PERCENT_PAD = INDEX_TMP_PAD
INDEX_INPUT_PERCENT_TEXT = '%'
INDEX_INPUT_FINAL_PRICE_SIZE = FINAL_PRICE_SIZE
INDEX_INPUT_FINAL_PRICE_PAD = INDEX_TMP_PAD
INDEX_INPUT_FINAL_PRICE_TEXT = 'PF'
INDEX_INPUT_AMOUNT_SIZE = AMOUNT_SIZE
INDEX_INPUT_AMOUNT_PAD = INDEX_TMP_PAD
INDEX_INPUT_AMOUNT_TEXT = 'CANTIDAD'
INDEX_INPUT_SUPPLIER_SIZE = SUPPLIER_SIZE
INDEX_INPUT_SUPPLIER_PAD = INDEX_TMP_PAD
INDEX_INPUT_SUPPLIER_TEXT = 'PROVEEDOR'
# FINDER
FINDER_INPUT_KEY = ',finder_input'
FINDER_INPUT_SIZE = (20, 1)
FINDER_INPUT_PAD = ((0, 4), (0, 0))
FINDER_BUTTON_KEY = ',search'
FINDER_BUTTON_PAD = S_TMP_PAD
FINDER_BUTTON_TEXT = '🔎'
FINDER_BUTTON_TOOLTIP = 'BUSCAR'
# PRE_SELL
PRE_SELL_BUTTON_KEY = ',pre_sell'
PRE_SELL_BUTTON_TEXT = '📤'
PRE_SELL_BUTTON_TOOLTIP = 'REALIZAR PRE-VENTA'
PRE_SELL_BUTTON_PAD = ((4, 4), (2, 2))
# PRE_BUY
PRE_BUY_BUTTON_KEY = ',pre_buy'
PRE_BUY_BUTTON_TEXT = '📥'
PRE_BUY_BUTTON_TOOLTIP = 'REALIZAR PRE-COMPRA'
PRE_BUY_BUTTON_PAD = ((4, 4), (2, 2))
# SORTER
SORTER_COMBO_KEY = ',sorter_option'
SORTER_COMBO_SIZE = (10, 1)
SORTER_COMBO_PAD = S_TMP_PAD
SORTER_COMBO_TOOLTIP = 'CAMPO DE ORDEN'
SORTER_COMBO_STOCK_VALUES = ['NOMBRE', 'PU', 'STOCK']
SORTER_COMBO_SALES_VALUES = ['NOMBRE', 'PU', 'STOCK', 'CANTIDAD', 'PF']
SORTER_COMBO_BUYS_VALUES = [
    'NOMBRE', 'PU', 'STOCK', 'CANTIDAD', 'PF', 'PROVEEDOR'
]
SORTER_COMBO_ALL_VALUES = {
    'NOMBRE': 0,
    'PU': 1,
    'STOCK': 2,
    'CANTIDAD': 3,
    'PF': 4,
    'PROVEEDOR': 5
}
SORTER_BUTTON_UP_KEY = ',sort_list_min_max'
SORTER_BUTTON_DOWN_KEY = ',sort_list_max_min'
SORTER_BUTTON_PAD = S_TMP_PAD
SORTER_BUTTON_UP_TEXT = 'A..Z'
SORTER_BUTTON_DOWN_TEXT = 'Z..A'
SORTER_BUTTON_UP_TOOLTIP = 'ORDENAR DE MENOR A MAYOR'
SORTER_BUTTON_DOWN_TOOLTIP = 'ORDENAR DE MAYOR A MENOR'
# THEME
THEME_BUTTON_KEY = ',change_theme'
THEME_BUTTON_PAD = ((4, 4), (2, 2))
THEME_BUTTON_DAY_TEXT = '☀️'
THEME_BUTTON_NIGHT_TEXT = '🌜'
THEME_BUTTON_TOOLTIP = 'CAMBIAR TEMA VISUAL'
# UNCHECK
UNCHECK_BUTTON_KEY = ',uncheck_records'
UNCHECK_BUTTON_PAD = ((4, 0), (0, 0))
UNCHECK_BUTTON_TEXT = '✖️'
UNCHECK_BUTTON_TOOLTIP = 'DESELECCIONAR TODO'
# CHECK_ALL
CHECK_ALL_BUTTON_PAD = ((0, 0), (0, 0))
CHECK_ALL_BUTTON_TEXT = '✔'
CHECK_ALL_BUTTON_TOOLTIP = 'SELECCIONAR TODO'
# COLLECT
COLLECT_BUTTON_KEY = ',collect_unit_prices'
COLLECT_BUTTON_PAD = ((4, 4), (2, 2))
COLLECT_BUTTON_TEXT = '🗃️'
COLLECT_BUTTON_TOOLTIP = 'OBTENER PRECIO Y STOCK'
# REMOVER
REMOVER_COMBO_KEY = ',REMOVER_option'
REMOVER_COMBO_SIZE = (15, 1)
REMOVER_COMBO_PAD = S_TMP_PAD
REMOVER_BUTTON_KEY = ',remove_records'
REMOVER_BUTTON_PAD = S_TMP_PAD
REMOVER_BUTTON_TEXT = '🗑️'
REMOVER_BUTTON_TOOLTIP = 'REMOVER REGISTROS'
STOCK_SECTION_REMOVER_OPTIONS = ['SELECCIONADOS', 'VACÍOS']
SALE_SECTION_REMOVER_OPTIONS = ['SELECCIONADOS']
# APPLY
APPLY_BUTTON_KEY = ',apply'
APPLY_BUTTON_PAD = ((4, 4), (2, 2))
APPLY_BUTTON_TEXT = '📝'
APPLY_BUTTON_TOOLTIP = 'APLICAR PORCENTAJE\nY CALCULAR EL PRECIO'
# ADDER
ADDER_SPIN_KEY = ',how_many_add'
ADDER_SPIN_SIZE = SPIN_SIZE
ADDER_SPIN_PAD = S_TMP_PAD
ADDER_SPIN_VALUES = [i for i in range(1, 30, 2)]
ADDER_BUTTON_KEY = ',add_records'
ADDER_BUTTON_PAD = S_TMP_PAD
ADDER_BUTTON_TEXT = '➕'
ADDER_BUTTON_TOOLTIP = 'AGREGAR REGISTROS',
# SAVE_AS
SAVE_AS_BUTTON_KEY = ',export'
SAVE_AS_BUTTON_PAD = ((0, 4), (2, 2))
SAVE_AS_BUTTON_TEXT = '💾'
SAVE_AS_BUTTON_TOOLTIP = 'GUARDAR CÓMO Y ABRIR'
SAVE_AS_BUTTON_INITIAL_FOLDER = DESKTOP + f'Reporte {DATE()} {TIME()}.csv'
# COMMERCE
COMMERCE_BUTTON_KEY = ',commerce'
COMMERCE_BUTTON_PAD = ((4, 4), (2, 2))
COMMERCE_BUTTON_TEXT = '🛒'
COMMERCE_BUTTON_TOOLTIP = 'REALIZAR COMERCIO'
# TOTAL_PRICE
TOTAL_PRICE_KEY = 'total_price'
TOTAL_PRICE_SIZE = S_TMP_SIZE
TOTAL_PRICE_PAD = S_TMP_PAD
# SECURE_MODE
SECURE_MODE_BUTTON_PAD = ((4, 4), (2, 2))
SECURE_LOCK_MODE_BUTTON_TEXT = '🔐'
SECURE_UNLOCK_MODE_BUTTON_TEXT = '🔓'
SECURE_MODE_BUTTON_TOOLTIP = 'BLOQUEAR/DESBLOQUEAR\nREGISTROS'
# IMAGE
BUTTON_IMAGE = b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAA9ElEQVQ4T3VTWRYDMQiS+x/aPgWX2HY+ZkkiAjKwuJB3g5s5+Om6c6E24qmzhnxVKRf7AiGiOI/BzBtIHREtYEAcdi9gMqn6g+nZnaAikl9N63n/U5zi2FPNEkAo2mhMqFsfLilRQ2lt2euBiKZLbnDISyIVfZ46moIfwpO091KS7dmcTqwpFPGRU9PrebVzBI4BSMIQmwxwbTxebmc02JsTO80rW6N1RUQesE45cM0kKOWET9qaSQleyM0g9Na1O++Zn7xSwkzyB2FpfXP6JkypLev4gxCaUr5NLN9rf0f5B8c97zdA5NU5eLSuP/icksGT7Q/rqoAi4wjvpQAAAABJRU5ErkJggg=='
BUTTON_IMAGE_SIZE = (52, 10)
BUTTON_LITTLE_IMAGE_SIZE = (20, 10)
